
package projetJavaEx1.vue.graph;

import java.awt.Color;
import javax.swing.JOptionPane;
import projetJavaEx1.modele.Modele;
import projetJavaEx1.mesclassesCEG.Groupe;

/**
 *
 * @author ogun.ark
 */


public class ajoutGroupe extends javax.swing.JPanel {

    private Modele m;

    public ajoutGroupe() {
        initComponents();
    }

    public void setModele(Modele m) {
        this.m = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcodegr = new javax.swing.JLabel();
        tfcodegr = new javax.swing.JTextField();
        jintitulegr = new javax.swing.JLabel();
        tfintitulegr = new javax.swing.JTextField();
        jniveau = new javax.swing.JLabel();
        tfniveau = new javax.swing.JTextField();
        btclear = new javax.swing.JButton();
        javax.swing.JButton btok = new javax.swing.JButton();

        setBackground(new java.awt.Color(218, 0, 0));
        setLayout(new java.awt.GridLayout(4, 3, 5, 2));

        jcodegr.setText("Code groupe");
        add(jcodegr);

        tfcodegr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcodegrActionPerformed(evt);
            }
        });
        add(tfcodegr);

        jintitulegr.setText("Intitule");
        add(jintitulegr);

        tfintitulegr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfintitulegrActionPerformed(evt);
            }
        });
        add(tfintitulegr);

        jniveau.setText("Niveau");
        add(jniveau);

        tfniveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfniveauActionPerformed(evt);
            }
        });
        add(tfniveau);

        btclear.setText("CLEAR");
        btclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclearActionPerformed(evt);
            }
        });
        add(btclear);

        btok.setText("OK");
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });
        add(btok);
    }// </editor-fold>//GEN-END:initComponents

    private void tfintitulegrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfintitulegrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfintitulegrActionPerformed

    private void tfniveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfniveauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfniveauActionPerformed

    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed
        tfcodegr.setBackground(Color.white);
        tfintitulegr.setBackground(Color.white);
        tfniveau.setBackground(Color.white);

        boolean erreur = false;
        String codegr = tfcodegr.getText();
        if (codegr.trim().equals("")) {
            erreur = true;
            tfcodegr.setBackground(Color.ORANGE);
        }
        String intitule = tfintitulegr.getText();
        if (intitule.trim().equals("")) {
            erreur = true;
            tfintitulegr.setBackground(Color.ORANGE);
        }
        String niveau = tfniveau.getText();
        if (niveau.trim().equals("")) {
            erreur = true;
            tfniveau.setBackground(Color.ORANGE);
        }

         if (!erreur) {
            Groupe g = new Groupe(codegr, intitule, niveau);
            
            String msg = m.ajoutGroupe(g);
            JOptionPane.showMessageDialog(this, msg, "Résultat", JOptionPane.INFORMATION_MESSAGE);
        } 
         else {
            if(erreur) JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs", "Erreur", JOptionPane.ERROR_MESSAGE);
            
        }
        
        

    }//GEN-LAST:event_btokActionPerformed

    private void btclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclearActionPerformed
        tfcodegr.setText("");
        tfintitulegr.setText("");
        tfniveau.setText("");
        tfcodegr.setBackground(Color.white);
        tfintitulegr.setBackground(Color.white);
        tfniveau.setBackground(Color.white);
    }//GEN-LAST:event_btclearActionPerformed

    private void tfcodegrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcodegrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcodegrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btclear;
    private javax.swing.JLabel jcodegr;
    private javax.swing.JLabel jintitulegr;
    private javax.swing.JLabel jniveau;
    private javax.swing.JTextField tfcodegr;
    private javax.swing.JTextField tfintitulegr;
    private javax.swing.JTextField tfniveau;
    // End of variables declaration//GEN-END:variables

}
