
package projetJavaEx1.vue.graph;

import java.awt.Color;
import javax.swing.JOptionPane;
import projetJavaEx1.modele.Modele;
import projetJavaEx1.mesclassesCEG.*;

/**
 *
 * @author ogun.ark
 */

public class ajoutCours extends javax.swing.JPanel {

    private Modele m;

    public ajoutCours() {
        initComponents();
    }

    public void setModele(Modele m) {
        this.m = m;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcodec = new javax.swing.JLabel();
        tfcodec = new javax.swing.JTextField();
        jnbr = new javax.swing.JLabel();
        tfnbr = new javax.swing.JTextField();
        jintitule = new javax.swing.JLabel();
        tfintitule = new javax.swing.JTextField();
        btclear = new javax.swing.JButton();
        javax.swing.JButton btok = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(4, 3, 5, 2));

        jcodec.setText("Code");
        add(jcodec);

        tfcodec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfcodecActionPerformed(evt);
            }
        });
        add(tfcodec);

        jnbr.setText("Nombre d'heure");
        add(jnbr);

        tfnbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnbrActionPerformed(evt);
            }
        });
        add(tfnbr);

        jintitule.setText("Intitule");
        add(jintitule);

        tfintitule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfintituleActionPerformed(evt);
            }
        });
        add(tfintitule);

        btclear.setText("CLEAR");
        btclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btclearActionPerformed(evt);
            }
        });
        add(btclear);

        btok.setText("Ajouter");
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });
        add(btok);
    }// </editor-fold>//GEN-END:initComponents

    private void tfnbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnbrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnbrActionPerformed

    private void tfintituleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfintituleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfintituleActionPerformed

    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed
        tfcodec.setBackground(Color.white);
        tfnbr.setBackground(Color.white);
        tfintitule.setBackground(Color.white);

        boolean erreur = false;
        String code = tfcodec.getText();
        if (code.trim().equals("")) {
            erreur = true;
            tfcodec.setBackground(Color.ORANGE);
        }
        String nbr = tfnbr.getText();
        int nbra = 0;
        try {
            nbra = Integer.parseInt(nbr);
        } catch (NumberFormatException e) {
            erreur = true;
            tfnbr.setBackground(Color.ORANGE);
        }
        String intitule = tfintitule.getText();
        if (intitule.trim().equals("")) {
            erreur = true;
            tfintitule.setBackground(Color.ORANGE);
        }

        if (!erreur) {
            Cours crs = null;
            Cours.CoursBuilder c = new Cours.CoursBuilder();
            c.setCodec(code).setNbrha(nbra).setIntitulec(intitule);
            try {
                crs = c.build();
            } catch (Exception e) {
                System.out.println("Erreur de création" + e);
            }
            
            String msg = m.ajoutCours(crs);
            JOptionPane.showMessageDialog(this, msg, "Résultat", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs", "Erreur", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_btokActionPerformed

    private void btclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btclearActionPerformed
        tfcodec.setText("");
        tfnbr.setText("");
        tfintitule.setText("");
        tfcodec.setBackground(Color.white);
        tfnbr.setBackground(Color.white);
        tfintitule.setBackground(Color.white);
    }//GEN-LAST:event_btclearActionPerformed

    private void tfcodecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfcodecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfcodecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btclear;
    private javax.swing.JLabel jcodec;
    private javax.swing.JLabel jintitule;
    private javax.swing.JLabel jnbr;
    private javax.swing.JTextField tfcodec;
    private javax.swing.JTextField tfintitule;
    private javax.swing.JTextField tfnbr;
    // End of variables declaration//GEN-END:variables

}
